### ISSUE TITLE
cli output is wrong(?)

### ISSUE THREAD

**Issue by stasoid** [Radvylf/rSNBATWPL#2]
I encountered this issue when tried to run [this program](https://codegolf.stackexchange.com/a/248071). It [prints 4 on dso](https://dso.surge.sh/#@WyJyYWlzaW4tYmF0d2FmZmxlIixudWxsLCIxIytpaWlpaWlpaWlva2gtXFxjYXRjb2RlYFxcIz02XFxmb250XFxtPWNtcjEwXFxtXG4xNCNcXGVuZDtcbjQrMCNhIC96QCBNb09Nb09Nb09Nb09Nb09Nb09Nb09cbnByaW50KDgtKDIqNS0zKSsoMS8yKSoxMCsxKzErMSsxKzErMSsxKzErMSsxKzEtMS0xLTEtMS0xLTEtMS0xLTEtMS0xKSMhKysrKytQICMrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKy5cbjArMCNhIF5Nb09Nb09Nb09Nb09Nb09Nb09PT01cbi0xKi0xMCs0XzMiLCIiLCIiLCIiXQ==), but noting with `node rsnbatwpl-cli.js file`. This is because cli prints only `sprints`, but DSO prints [`prints+'\n'+out`](https://github.com/chunkybanana/do-stuff-online/blob/9839903bf20b263f759905e904129a44588b5d07/langs/raisin-batwaffle.js#L78). I am guessing DSO's behavior is more correct because `rsnbatwpl.html` also prints 4.

**Comment by Radvylf** [comment]
No, this has to do with full program vs. snippet, same as JS or Python. Just like how if you run `node` and type `4` it prints `4`, but running a JS file containing just `4` won't print anything. Any answers that rely on the REPL/`rsnbatwpl.html`'s behavior of printing the output of the last statement is invalid since it's a snippet. Sorry for any confusion.
